=== gregersn/whathappened/app/character/schema/coc.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "meta": {
            "type": "object",
            "properties": {
                "Title": {"type": "string"},
                "Creator": {"type": "string"},
                "CreateDate": {"type": "string"},
                "GameName": {"type": "string"},
                "GameVersion": {"type": "string"},
                "GameType": {
                    "type": "string",
                    "enum": ["Classic (1920's)", "Modern"]
                },
                "Disclaimer": {"type": "string"},
                "Version": {"type": "string", "value": "0.0.1"}
            }
        },
        "personalia": {
            "type": "object",
            "properties": {
                "Name": {"type": "string"},
                "Occupation": {"type": "string"},
                "Gender": {"type": "string"},
                "Age": {"type": "string"},
                "Birthplace": {"type": "string"},
                "Residence": {"type": "string"}
            }
        },
        "characteristics": {
            "type": "object",
            "properties": {
                "STR": {"type": "string"},
                "DEX": {"type": "string"},
                "INT": {"type": "string"},
                "CON": {"type": "string"},
                "APP": {"type": "string"},
                "POW": {"type": "string"},
                "SIZ": {"type": "string"},
                "EDU": {"type": "string"},
                "Move": {"type": "string"},
                "Luck": {"type": "string"},
                "LuckMax": {"type": "string"},
                "Sanity": {"type": "string"},
                "SanityStart": {"type": "string"},
                "SanityMax": {"type": "string"},
                "MagicPts": {"type": "string"},
                "MagicPtsMax": {"type": "string"},
                "HitPts": {"type": "string"},
                "HitPtsMax": {"type": "string"}
            }
        },
        "skills": {
            "type": "array",
            "items": {
                    "type": "object",
                    "properties": {
                        "name": {"type": "string"},
                        "value": {"type": "string"}
                    }
            }
        },
        "weapons": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "regular": {"type": "string"},
                    "damage": {"type": "string"},
                    "range": {"type": "string"},
                    "attacks": {"type": "string"},
                    "ammo": {"type": "string"},
                    "malf": {"type": "string"}
                }
            }
        },
        "combat": {
            "type": "object",
            "properties": {
                "DamageBonus": {"type": "string"},
                "Build": {"type": "string"},
                "Dodge": {"type": "string"}
            }
        },
        "backstory": {
            "type": "object",
            "properties": {
                "description": {
                    "anyOf": [{"type": "string"}, {"type": "null"}]
                },
                "traits": {
                    "anyOf": [{"type": "string"}, {"type": "null"}]
                },
                "ideology": {
                    "anyOf": [{"type": "string"}, {"type": "null"}]
                },
                "injurues": {
                    "anyOf": [{"type": "string"}, {"type": "null"}]
                },
                "people": {
                    "anyOf": [{"type": "string"}, {"type": "null"}]
                },
                "phobias": {
                    "anyOf": [{"type": "string"}, {"type": "null"}]
                },
                "locations": {
                    "anyOf": [{"type": "string"}, {"type": "null"}]
                },
                "tomes": {
                    "anyOf": [{"type": "string"}, {"type": "null"}]
                },
                "possessions": {
                    "anyOf": [{"type": "string"}, {"type": "null"}]
                },
                "encounters": {
                    "anyOf": [{"type": "string"}, {"type": "null"}]
                }
            }
        },
        "possessions": {
            "anyOf": [{"type": "array"}, {"type": "null"}]
        },
        "cash": {
            "type": "object",
            "properties": {
                "spending": {"type": "string"},
                "cash": {"type": "string"},
                "assets": {"type": "string"}
            }
        },
        "assets": {
            "anyOf": [{"type": "object"}, {"type": "null"}]
        }
    }
}

=== gregersn/whathappened/tests/coc7e/testchar.json
{
    "meta": {
        "Title": "Test Character",
        "Creator": "What happened? A TTRPG utility",
        "CreateDate": "0.2591436",
        "GameName": "Call of Cthulhu TM",
        "GameVersion": "7th Edition",
        "GameType": "Classic (1920's)",
        "Disclaimer": "The developer has not rolled for sanity",
        "Version": "0.0.1"
    },
    "personalia": {
        "Name": "Test Character",
        "Occupation": "Drifter",
        "Archetype": null,
        "Gender": "Male",
        "Age": "46",
        "Birthplace": "Arkham",
        "Residence": "Arkham",
        "Portrait": null
    },
    "characteristics": {
        "STR": "50",
        "DEX": "52",
        "INT": "80",
        "CON": "65",
        "APP": "60",
        "POW": "65",
        "SIZ": "65",
        "EDU": "69",
        "Move": "7",
        "Luck": "60",
        "LuckMax": "60",
        "Sanity": "63",
        "SanityStart": "65",
        "SanityMax": "98",
        "MagicPts": "13",
        "MagicPtsMax": "13",
        "HitPts": "13",
        "HitPtsMax": "13",
        "DamageBonus": "0",
        "Build": "0",
        "OccupationSkillPoints": "0",
        "PersonalInterestSkillPoints": "0"
    },
    "skills": [
        {
            "name": "Accounting",
            "value": "5"
        },
        {
            "name": "Anthropology",
            "value": "1"
        },
        {
            "name": "Appraise",
            "value": "5"
        },
        {
            "name": "Archaeology",
            "value": "1"
        },
        {
            "name": "Art/Craft",
            "specializations": "true",
            "value": "5",
            "subskills": [
                {
                    "name": "Technical Drawing",
                    "value": "50",
                    "occupation": true
                }
            ]
        },
        {
            "name": "Charm",
            "value": "15"
        },
        {
            "name": "Climb",
            "value": "20"
        },
        {
            "name": "Credit Rating",
            "value": "50"
        },
        {
            "name": "Cthulhu Mythos",
            "value": "1"
        },
        {
            "name": "Disguise",
            "value": "5"
        },
        {
            "name": "Dodge",
            "value": "26"
        },
        {
            "name": "Drive Auto",
            "value": "20"
        },
        {
            "name": "Electrical Repair",
            "value": "81",
            "occupation": true
        },
        {
            "name": "Fast Talk",
            "value": "5"
        },
        {
            "name": "Custom skill",
            "value": "23"
        },
        {
            "name": "Fighting",
            "specializations": "true",
            "value": "0",
            "subskills": [
                {
                    "name": "Brawl",
                    "value": "25"
                }
            ]
        },
        {
            "name": "Firearms",
            "specializations": "true",
            "value": "0",
            "subskills": [
                {
                    "name": "Handgun",
                    "value": "20"
                },
                {
                    "name": "Rifle/Shotgun",
                    "value": "25"
                }
            ]
        },
        {
            "name": "First Aid",
            "value": "30",
            "checked": false
        },
        {
            "name": "History",
            "value": "5"
        },
        {
            "name": "Intimidate",
            "value": "15"
        },
        {
            "name": "Jump",
            "value": "20"
        },
        {
            "name": "Language (Other)",
            "specializations": "true",
            "value": "1",
            "subskills": [
                {
                    "name": "English",
                    "value": "50"
                }
            ]
        },
        {
            "name": "Language (Own)",
            "value": "69"
        },
        {
            "name": "Law",
            "value": "5"
        },
        {
            "name": "Library Use",
            "value": "57",
            "occupation": true,
            "checked": false
        },
        {
            "name": "Listen",
            "value": "20"
        },
        {
            "name": "Locksmith",
            "value": "51"
        },
        {
            "name": "Mechanical Repair",
            "value": "60",
            "occupation": true
        },
        {
            "name": "Medicine",
            "value": "1"
        },
        {
            "name": "Natural World",
            "value": "60"
        },
        {
            "name": "Navigate",
            "value": "10"
        },
        {
            "name": "Occult",
            "value": "10",
            "checked": false
        },
        {
            "name": "Operate Heavy Machine",
            "value": "1",
            "occupation": true
        },
        {
            "name": "Persuade",
            "value": "10"
        },
        {
            "name": "Pilot",
            "specializations": "true",
            "value": "1"
        },
        {
            "name": "Psychology",
            "value": "10"
        },
        {
            "name": "Psychoanalysis",
            "value": "1"
        },
        {
            "name": "Ride",
            "value": "5"
        },
        {
            "name": "Science",
            "specializations": "true",
            "value": "1",
            "subskills": [
                {
                    "name": "Engineering",
                    "value": "61",
                    "occupation": true
                },
                {
                    "name": "Physics",
                    "value": "41",
                    "occupation": true
                }
            ]
        },
        {
            "name": "Sleight of Hand",
            "value": "10"
        },
        {
            "name": "Spot Hidden",
            "value": "25"
        },
        {
            "name": "Stealth",
            "value": "20"
        },
        {
            "name": "Survival",
            "specializations": "true",
            "value": "10"
        },
        {
            "name": "Swim",
            "value": "20"
        },
        {
            "name": "Throw",
            "value": "20"
        },
        {
            "name": "Track",
            "value": "10"
        }
    ],
    "weapons": [
        {
            "name": "Unarmed",
            "regular": "10",
            "damage": "1d3 + db",
            "range": "-",
            "attacks": "1",
            "ammo": "-",
            "malf": "-"
        },
        {
            "name": "Knife",
            "regular": "11",
            "damage": "1d4 + 2 + db",
            "range": "-",
            "attacks": "-",
            "ammo": "-",
            "malf": "-"
        }
    ],
    "combat": {
        "DamageBonus": "0",
        "Build": "0",
        "Dodge": "0"
    },
    "backstory": {
        "description": null,
        "traits": null,
        "ideology": null,
        "injurues": null,
        "people": "None",
        "phobias": null,
        "locations": null,
        "tomes": null,
        "possessions": null,
        "encounters": null
    },
    "possessions": [
        "A",
        "list",
        "of",
        "possessions"
    ],
    "cash": {
        "spending": "5",
        "cash": "25",
        "assets": "250"
    },
    "assets": "A description of assets"
}
